version: '3'
services:
  app:
    container_name: expense-manager-app
    image: emapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    networks:
      - octopus_bridge
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: expense-manager-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: expense_manager
    #volumes:
     # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
         - octopus_bridge
networks:
  octopus_bridge:
       driver: bridge
       external: true
