spring:
  application:
    name: expense-manager
    admin:
      enabled: true

  data:
    jpa:
      repositories:
        enabled: true
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
      sort:
        sort-parameter: sort
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        type: debug
        use_sql_comments: true
  datasource:
    url: jdbc:mysql://localhost:3306/expense_manager
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
  flyway:
    clean-on-validation-error: true
    enabled: true
    locations: classpath:db/migration
    schemas: expense_manager
    create-schemas: true
  sql:
    init:
      mode: never
      data-locations: ./init.sql
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
management:
  endpoint:
    flyway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,flyway
springdoc:
  show-actuator: true
sync-service:
  vendor-url: http://SYNC-SERVICE/api/v1/sync/get/vendors
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    enabled: true
logging:
  include-application-name: true
server:
  port: 10000