spring:
  data:
    jpa:
      repositories:
        enabled: true
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
      sort:
        sort-parameter: sort

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        type: debug
        use_sql_comments: true

  datasource:
    url: jdbc:mysql://localhost:3306/expense_manager
    username: em_rw_user
    password: adminUser
    driver-class-name: com.mysql.cj.jdbc.Driver

  docker:
    compose:
      enabled: true
      file: docker-compose.yml
  flyway:
    clean-on-validation-error: true
    enabled: true
    locations: classpath:db/migration
    schemas: expense_manager
    create-schemas: true
rsa:
    private-key: classpath:certs/private.pem
    public-key: classpath:certs/public.pem
management:
  endpoint:
    flyway:
      enabled: true
    health:
        show-details: always