version: 2.1

orbs:
  gradle: circleci/gradle@1.0.3

executors:
  machine_executor_amd64:
    machine:
      image: ubuntu-2204:2022.04.2
    environment:
      architecture: "amd64"
      platform: "linux/amd64"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build_and_test

jobs:
  build_and_test:
    executor: machine_executor_amd64
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "build.gradle.kts" }}
      - run:
         name: Run Spotless check
         command: ./gradlew spotlessCheck
      - run:
          name: Run Unit Tests
          command: ./gradlew test
      - run:
          name: Decode Keys
          command: |
            mkdir -p ./src/main/resources/certs
            echo $JWT_PRIVATE_KEY_BASE64 | base64 --decode > ./src/main/resources/certs/private.pem
            echo $JWT_PUBLIC_KEY_BASE64 | base64 --decode > ./src/main/resources/certs/public.pem
            echo $JWT_KEY_PAIR | base64 --decode > ./src/main/resources/certs/keypair.pem
            
      - run:
          name: Run Integration Tests with Testcontainers
          command: ./gradlew testInteg 
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache-{{ checksum "build.gradle.kts" }}
