version: 2.1

orbs:
  gradle: circleci/gradle@1.0.3

executors:
  machine_executor_amd64:
    machine:
      image: ubuntu-2204:2022.04.2
    environment:
      architecture: "amd64"
      platform: "linux/amd64"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build_and_test

jobs:
  build_and_test:
    executor: machine_executor_amd64
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "build.gradle" }}
     # - run:
      #    name: clean
       #   command: ./gradlew clean build 
      - run:
          name: Run Unit Tests
          command: ./gradlew test
      - run:
          name: Decode Keys
          command: |
            mkdir -p ./src/main/resources/certs
            mkdir -p ./src/test/resources/certs
            echo $JWT_PRIVATE_KEY_BASE64 | base64 --decode > ./src/main/resources/certs/private_key.pem
            echo $JWT_PUBLIC_KEY_BASE64 | base64 --decode > ./src/main/resources/certs/public_key.pem
            echo $JWT_PRIVATE_KEY_BASE64 | base64 --decode > ./src/test/resources/certs/private_key.pem
            echo $JWT_PUBLIC_KEY_BASE64 | base64 --decode > ./src/test/resources/certs/public_key.pem
            echo $JWT_KEY_PAIR | base64 --decode > ./src/main/resources/certs/keypaid.pem
            cat ./src/main/resources/certs/public_key.pem
            cat ./src/main/resources/certs/private_key.pem
      # Uncomment the following lines when you want to enable integration tests
      - run:
          name: Run Integration Tests with Testcontainers
          command: ./gradlew testInteg --scan
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache-{{ checksum "build.gradle" }}
